org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.87
neo_version_range=[26,)
loader_version_range=[4,)

mod_id=nestle
mod_name=Nestle
mod_license=MIT
mod_version=0.1.2-neoforge+mc26.1.2
mod_group_id=io.github.kunosayo
mod_authors=KunoSayo
mod_description=Nestle each other!
